import bottlenose
from config import AMAZON_ACCESS_KEY, AMAZON_SECRET_KEY, AMAZON_TAG,\
    AMAZON_REGION

amazon = bottlenose.Amazon(AMAZON_ACCESS_KEY, AMAZON_SECRET_KEY, AMAZON_TAG, Region=AMAZON_REGION)
